apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-protect-bd-config-pvc
  namespace: nginx-ingress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-protect-bundles-pvc
  namespace: nginx-ingress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
